name: Debug OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        run: |
          TOKEN="$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=test-audience")"
          echo "OIDC Token Payload:"
          echo $TOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson'
